config/routes.rb
Notepad::Application.routes.draw do

  get "map/index"
  use_doorkeeper
  devise_for :users

  resources :notes
  resources :profiles

  root 'high_voltage/pages#show', id: "index"

  namespace :api do
    namespace :v1 do
      resources :notes, except: [ :new, :edit ]
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base

  validates :title, :body, presence: true
  validates :user_id, presence: true

  belongs_to :user

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  validates :user_id, presence: true
  validates :name, :location, presence: true

  belongs_to :user

  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :notes, :dependent => :destroy

  has_many :oauth_applications, class_name: 'Doorkeeper::Application', as: :owner
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ActionController::Base
      # Prevent CSRF attacks by raising an exception.
      # For APIs, you may want to use :null_session instead.
      protect_from_forgery with: :null_session # :exception

      def current_resource_owner
        User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
      end

    end
  end
end

app/controllers/api/v1/notes_controller.rb
module Api
  module V1
    class NotesController < BaseController

      doorkeeper_for :all
      before_action :set_note, only: [:show, :update, :destroy]

      def index
        #@notes = Note.all
        @notes = current_resource_owner.notes
        render json: @notes, status: 200
      end

      def create
        @note = current_resource_owner.notes.new(note_params)

        if @note.save
          render nothing: true, status: 204
        else
          render json: @note.errors, status: 422
        end
      end

      def show
        render json: @note, status: 200
      end

      def update
        if @note.update(note_params)
          render json: @note, status: 200
        else
          render json: @note.errors, status: 422
        end
      end

      def destroy
        @note.destroy
        head 204
      end


      private

      def set_note
        @note = current_resource_owner.notes.find(params[:id])
      end

      def note_params
        params.require(:note).permit(:title, :body, :user_id)
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with:  :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @profiles = Profile.all

    @hash = Gmaps4rails.build_markers(@profiles) do |profile, marker|
      marker.lat profile.latitude
      marker.lng profile.longitude
      marker.title profile.location
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter :authenticate_user!

  def index
    #@notes = Note.all
    @notes = current_user.notes.order("created_at DESC")
  end

  def new
    #@note = Note.new
    @note = current_user.notes.new
  end

  def create
    #@note = Note.new(note_params)
    @note = current_user.notes.new(note_params)

    if @note.save
      respond_to do |format|
        format.html { redirect_to @note, notice: "Nota Guardada!" }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @note }
        format.js { render "error_create.js.erb" }
      end
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def destroy
    #@note = Note.find(params[:id])
    @note = current_user.notes.find(params[:id])
    @note.destroy

    redirect_to notes_path, notice: "Nota Eliminada!"
  end

  private
  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/oauth/applications_controller.rb
class Oauth::ApplicationsController < Doorkeeper::ApplicationsController
  before_filter :authenticate_user!

  def index
    @applications = current_user.oauth_applications
  end

  # only needed if each application must have some owner
  def create
    @application = Doorkeeper::Application.new(application_params)
    @application.owner = current_user if Doorkeeper.configuration.confirm_application_owner?
    if @application.save
      flash[:notice] = I18n.t(:notice, :scope => [:doorkeeper, :flash, :applications, :create])
      respond_with [:oauth, @application]
    else
      render :new
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @profile = current_user.profile
  end

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to profiles_url, notice: "Tu perfil ha sido creado"
    else
      flash.now[:danger] = "Hubo un error, revise y reintente"
      render :new 
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile

    if @profile.update(profile_params)
      redirect_to profiles_url, notice: "Perfil Actualizado"
    else
      flash.now[:danger] = "Hubo un error, revise y reintente"
      render :edit
    end
  end


  private

  def profile_params
    params.require(:profile).permit(:name, :location, :web, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def empty_profile?(user)
    user.nil?
  end

  def show_name_or_email
    if empty_profile?(current_user.profile)
      return current_user.email
    else
      return current_user.profile.name
    end
  end

end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def to_markdown(text)
    sanitize Kramdown::Document.new(text).to_html
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Notas</a>
    </div>
    <div class="navbar-collapse collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Mapa de usuarios", map_index_path %></li>
        <li><a href="http://jam.net.ve">Web</a></li>
        <li><a href="http://jam.net.ve/cv">CV</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "Perfil", profiles_path %></li>
          <li><%= link_to show_name_or_email, edit_user_registration_path %></li>
          <li><%= link_to "Mis notas", notes_path %></li>
          <li><%= link_to "Salir", destroy_user_session_path,
                                   method: :delete %></li>
        <% else %>
          <li><%= link_to "Entrar", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Notepad</title>
  <%= stylesheet_link_tag    "application",
                              media: "all",
                              "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navigation" %>
  <main role="main">
  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>
  </main>
</body>
</html>

app/views/map/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<h1>Mapa de usuarios.</h1>
<p>Mira de donde son los usuarios!</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/notes/_form.html.erb
<h1>Crear nota nueva</h1>
  <%= form_for :note, url: notes_path,
                      html: { class: "form-horizontal", role: "form" },
                      remote: true  do |f| %>

    <div class="form-group">
      <p>
        <%= f.text_field :title, class: "form-control",
                                 placeholder: "Titulo" %>
      </p>

      <p>
        <%= f.text_area :body, size: "60x5",
                              class: "form-control",
                        placeholder: "Contenido: Markdown es bienvenido!!!" %>
      </p>

      <p>
        <%= f.submit "Guardar", class: "btn btn-primary" %>
      </p>
    </div>
  <% end %>

app/views/notes/_note.html.erb
<%= div_for note do %>
<div class="table-responsive">
<table class="table table-hover ">
  <tr>
    <td><%= note.title %></td>
    <td class="text-center" ><%= to_markdown(note.body.truncate(150)) %></td>
    <td class="text-right" ><%= link_to 'Mostrar', note_path(note) %></br>
        <%= link_to 'Eliminar', note, method: :delete,
      data: { confirm: "Seguro?" } %></td>
  </tr>
</table>
</div>
<% end %>

app/views/notes/create.js.erb
$("#notes").prepend("<%= escape_javascript(render(@note)) %>");
$(".form-horizontal")[0].reset();

app/views/notes/error_create.js.erb
alert("<%= @note.errors.full_messages.to_sentence.html_safe %>");

app/views/notes/index.html.erb
<div id="new_note_form">
</div>

<%= link_to "Nueva nota",
            new_note_path(@note, :format => :js),
            :remote => true,
            :id => "new_note_link",
            class: "btn btn-primary btn-xs active",
            role: "button"%>

<h3><%= show_name_or_email  %>, Estas son tus notas </h3>
<div id="notes">
  <%= render @notes %>
</div>

app/views/notes/new.html.erb
<h1>Nota nueva</h1>

<%= render "form" %>

<%= link_to 'Atras', notes_path %>

app/views/notes/new.js.erb
$("<%= escape_javascript render(file: "notes/_form.html.erb") %>")
.appendTo("#new_note_form");

$(".form-horizontal").hide().slideDown();
$("#new_note_link").hide();

app/views/notes/show.html.erb
<section>
  <h1>Nota</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <p>
        <strong>Titulo:</strong>
        <%= @note.title.capitalize %>
        </p>
        <%= to_markdown(@note.body) %>
        <p>
        <%= link_to "Eliminar", @note, method: :delete,
          data: { confirm: "Seguro?" } %> |
          <%= link_to "Inicio", notes_path %>
          </p>
        </div>
      </div>
    </div>
  </section>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>Bienvenido a Notas.</h1>
  <p>Fragmentos de texto que solo tienen significado para ti.</p>
  <% if user_signed_in? %>
    <p><%= link_to "Ir a mis notas...", notes_path,
                    class: "btn btn-success btn-lg" %> </p>
  <% else %>
    <p><%= link_to "Registrate!", new_user_registration_path,
                    class: "btn btn-primary btn-lg" %></p>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>

    <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editar mi perfil</h1>

<%= render "form" %>

<%= link_to "Atras", profiles_path %>

app/views/profiles/index.html.erb
<h1>Mi Perfil</h1>

<% unless empty_profile?(@profile) %>

  <p>Nombre: <%= @profile.name %></p>
  <p>Ubicacion: <%= @profile.location %></p>
  <p>Web: <%= @profile.web %></p>
  <p>Bio: <%= @profile.bio %></p>
  <p>Latitud: <%= @profile.latitude %></p>
  <p>Longitud: <%= @profile.longitude %></p>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@profile.latitude}%2C#{@profile.longitude}" %><br />


  <%= link_to "Editar", edit_profile_path(@profile) %>

<% else %>
  <h4><%= show_name_or_email %> Todavia no tienes perfil</h4>
  <%= link_to "Crear mi perfil", new_profile_path, class: "btn btn-primary"  %>
<% end %>

app/views/profiles/new.html.erb
<h1>Crea tu perfil</h1>

<%= render "form" %>

<%= link_to "Atras", profiles_path %>